version: "3.8"
services:
  backend:
    build: .
    container_name: bee_backend
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB_NAME=bee_vision_db

  mongo:
    image: mongo:5.0
    container_name: bee_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
