version: "3.8"
services:
  backend:
    build: .
    container_name: bee_backend
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: ${MONGO_URI}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
    devices:
      - "/dev/video0:/dev/video0"
    privileged: true
    env_file:
      - .env
    volumes:
      - .:/app
      - ./data:/data
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload


  # mongo:
  #   image: mongo:5.0
  #   container_name: bee_mongo
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo_data:/data/db

volumes:
  mongo_data:
